/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./src/components/index/About.vue')['default']
    Carousel: typeof import('./src/components/carousel.vue')['default']
    Contact: typeof import('./src/components/index/Contact.vue')['default']
    Footer: typeof import('./src/components/common/Footer.vue')['default']
    Header: typeof import('./src/components/common/Header.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/index/Home.vue')['default']
    Main: typeof import('./src/components/index/Main.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Skill: typeof import('./src/components/index/Skill.vue')['default']
    Work: typeof import('./src/components/index/Work.vue')['default']
  }
}
